# P23 数组的ufunc广播机制

###### ufunc通用函数，能对array所有元素进行操作

In [1]:
import numpy as np

In [17]:
arr = np.arange(12).reshape(4,3)

In [18]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [19]:
arr1 = np.array([[1,-3,5],[-2,4,6],[8,-10,12],[3,-6.6,9.9]])

In [20]:
arr1

array([[  1. ,  -3. ,   5. ],
       [ -2. ,   4. ,   6. ],
       [  8. , -10. ,  12. ],
       [  3. ,  -6.6,   9.9]])

In [10]:
arr + arr1

array([[ 1. , -2. ,  7. ],
       [ 1. ,  8. , 11. ],
       [14. , -3. , 20. ],
       [12. ,  3.4, 20.9]])

In [11]:
arr2 = np.array([1,2,3])

In [12]:
arr2

array([1, 2, 3])

In [18]:
# 行列不同进行了广播机制
# 一维数组按行补齐，不一致使先补齐行数再运算
# 二维数组同上，哪个不齐先补哪个

In [15]:
arr + arr2

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11],
       [10, 12, 14]])

In [16]:
arr3 = np.array([1,2,3,4]).reshape(4,1)

In [17]:
arr3

array([[1],
       [2],
       [3],
       [4]])

In [19]:
arr + arr3

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [20]:
math = np.array([60,70,80,90,95,55])
english = math.copy()
cs = math.copy()

In [21]:
english

array([60, 70, 80, 90, 95, 55])

In [26]:
cs

array([60, 70, 80, 90, 95, 55])

In [22]:
total = math + english + cs

In [23]:
total

array([180, 210, 240, 270, 285, 165])

In [24]:
# add(,)
np.add(math,np.add(english,cs))

array([180, 210, 240, 270, 285, 165])

In [27]:
# subtract(,)
np.subtract(math,cs)

array([0, 0, 0, 0, 0, 0])

In [28]:
# divide(,) - 除
np.divide(math,cs)

array([1., 1., 1., 1., 1., 1.])

In [29]:
# multiply(,) - 乘
np.multiply(math,cs)

array([3600, 4900, 6400, 8100, 9025, 3025])

In [30]:
arr1

array([[  1. ,  -3. ,   5. ],
       [ -2. ,   4. ,   6. ],
       [  8. , -10. ,  12. ],
       [  3. ,  -6.6,   9.9]])

In [35]:
# power(,) - 目标函数的几次方
np.power(arr,3)

array([[   0,    1,    8],
       [  27,   64,  125],
       [ 216,  343,  512],
       [ 729, 1000, 1331]], dtype=int32)

In [36]:
s = np.array([1,3,5,7,9,2,4,6,8,10,1,2,3,4,3,2,1,2,3,4,3,2,1])

In [37]:
t = [3,4,5]

In [43]:
# in1d(x,y) - 判断y中元素是否再x中存在.in1d,1是数字1
np.in1d(s,t)

array([False,  True, False, False, False, False,  True, False, False,
       False, False, False,  True,  True,  True, False, False, False,
        True,  True, False, False])

In [47]:
# intersect1d(x,y) - 返回交集,数字1
np.intersect1d(t,s)

array([3, 4])

In [38]:
# unique - 去重
np.unique(s)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
arr == arr1

array([[False, False, False],
       [False,  True, False],
       [False, False, False],
       [False, False, False]])

In [51]:
# equal - 相等
# 同上
np.equal(arr, arr1)

array([[False, False, False],
       [False,  True, False],
       [False, False, False],
       [False, False, False]])

In [52]:
arr > arr1

array([[False,  True, False],
       [ True, False, False],
       [False,  True, False],
       [ True,  True,  True]])

In [53]:
# greater - 大于
# 同上
np.greater(arr,arr1)

array([[False,  True, False],
       [ True, False, False],
       [False,  True, False],
       [ True,  True,  True]])

In [54]:
# any() - 一真为真
np.greater(arr,arr1).any()

True

In [55]:
# all() - 一假为假
np.greater(arr,arr1).all()

False

In [57]:
n = [1,1,np.nan]

In [58]:
n

[1, 1, nan]

In [59]:
# isnan - 对空值进行判断
np.isnan(n)

array([False, False,  True])

# 搜索与排序 P24

In [4]:
import numpy as np

In [14]:
s = np.array([9,7,6,4,1,4,5,7,8,3,2,5,8,8,5,2,4])

In [5]:
# 升序
np.sort(s)
# 返回的是数组

array([1, 2, 2, 3, 4, 4, 4, 5, 5, 5, 6, 7, 7, 8, 8, 8, 9])

In [6]:
sorted(s)  
# 返回的是列表

[1, 2, 2, 3, 4, 4, 4, 5, 5, 5, 6, 7, 7, 8, 8, 8, 9]

In [8]:
# 降序
sorted(s,reverse = True)

[9, 8, 8, 8, 7, 7, 6, 5, 5, 5, 4, 4, 4, 3, 2, 2, 1]

In [9]:
# 转换为数组
np.array(sorted(s,reverse = True))

array([9, 8, 8, 8, 7, 7, 6, 5, 5, 5, 4, 4, 4, 3, 2, 2, 1])

In [10]:
# argsort - 排完序在原数据的索引位置
np.argsort(s)

array([ 4, 15, 10,  9, 16,  3,  5,  6, 11, 14,  2,  1,  7,  8, 12, 13,  0],
      dtype=int64)

In [12]:
# argmax - 最大数在原数据索引位置
np.argmax(s)

0

In [15]:
# 同上，找最小
s.argmin()

4

In [21]:
arr1

array([[  1. ,  -3. ,   5. ],
       [ -2. ,   4. ,   6. ],
       [  8. , -10. ,  12. ],
       [  3. ,  -6.6,   9.9]])

In [22]:
# 按行
arr1.argmax(axis = 1)

array([2, 2, 2, 2], dtype=int64)

In [24]:
# 按列
arr1.argmax(axis = 0)

array([2, 1, 2], dtype=int64)

In [25]:
# where(condition,x,y) - 条件语句
# 返回的是下标
np.where(arr1>5)
# (1,2) (2,0) (2,2) (3,2)

(array([1, 2, 2, 3], dtype=int64), array([2, 0, 2, 2], dtype=int64))

In [26]:
# 大于5返回1，否则返回0
np.where(arr1>5,1,0)

array([[0, 0, 0],
       [0, 0, 1],
       [1, 0, 1],
       [0, 0, 1]])

In [27]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [32]:
# 如果arr>arr1，返回arr1,否则返回arr
np.where(arr > arr1, arr1, arr)

array([[  0. ,  -3. ,   2. ],
       [ -2. ,   4. ,   5. ],
       [  6. , -10. ,   8. ],
       [  3. ,  -6.6,   9.9]])

In [34]:
# extract - 提取
# 如果arr > arr1,就提取arr1
np.extract(arr > arr1, arr1)

array([ -3. ,  -2. , -10. ,   3. ,  -6.6,   9.9])

In [36]:
arr1

array([[  1. ,  -3. ,   5. ],
       [ -2. ,   4. ,   6. ],
       [  8. , -10. ,  12. ],
       [  3. ,  -6.6,   9.9]])

In [35]:
arr > arr1

array([[False,  True, False],
       [ True, False, False],
       [False,  True, False],
       [ True,  True,  True]])