# 索引和切片 P20

In [2]:
import numpy as np

In [3]:
arr = np.arange(1,10)

In [4]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr[0]

1

In [6]:
arr[3:5]

array([4, 5])

In [7]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [8]:
arr[-1]

9

In [9]:
arr[-4:-2]

array([6, 7])

In [10]:
arr[4] = 250

In [11]:
arr

array([  1,   2,   3,   4, 250,   6,   7,   8,   9])

*浅拷贝，新元素改变，原元素也随着改变，类似c中的传地址

*视图上修改源数据也会改变

In [12]:
arr1 = arr

In [13]:
arr1

array([  1,   2,   3,   4, 250,   6,   7,   8,   9])

In [14]:
arr1[1:3] = (369,258)

In [15]:
arr1

array([  1, 369, 258,   4, 250,   6,   7,   8,   9])

In [16]:
arr

array([  1, 369, 258,   4, 250,   6,   7,   8,   9])

*copy - 深拷贝

In [17]:
arr2 = arr.copy()

In [18]:
arr2

array([  1, 369, 258,   4, 250,   6,   7,   8,   9])

In [19]:
arr2[6:8] = (22,33)

In [20]:
arr2

array([  1, 369, 258,   4, 250,   6,  22,  33,   9])

In [21]:
# 原数据不会改变
arr

array([  1, 369, 258,   4, 250,   6,   7,   8,   9])

In [93]:
data = ((1,3,5,-7,-90),(-2,4,-6,8,10),(22,33,-2,-5,-8),(-66,-22,33,9,13.114))

In [94]:
arr3 = np.array(data)

In [95]:
arr3

array([[  1.   ,   3.   ,   5.   ,  -7.   , -90.   ],
       [ -2.   ,   4.   ,  -6.   ,   8.   ,  10.   ],
       [ 22.   ,  33.   ,  -2.   ,  -5.   ,  -8.   ],
       [-66.   , -22.   ,  33.   ,   9.   ,  13.114]])

In [96]:
arr5 = arr3.copy()

In [25]:
arr3[3]

array([-66.   , -22.   ,  33.   ,   9.   ,  13.114])

In [26]:
arr3[3,1]

-22.0

In [27]:
arr3[:,2:4]

array([[ 5., -7.],
       [-6.,  8.],
       [-2., -5.],
       [33.,  9.]])

In [28]:
arr3[2:4]

array([[ 22.   ,  33.   ,  -2.   ,  -5.   ,  -8.   ],
       [-66.   , -22.   ,  33.   ,   9.   ,  13.114]])

In [29]:
# 从第二行第三列开始
arr3[1:,2:]

array([[-6.   ,  8.   , 10.   ],
       [-2.   , -5.   , -8.   ],
       [33.   ,  9.   , 13.114]])

In [30]:
arr3[2,1]

33.0

In [31]:
arr3 > 20

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [ True,  True, False, False, False],
       [False, False,  True, False, False]])

In [32]:
arr3[arr3>20]

array([22., 33., 33.])

In [33]:
# 取反
~(arr3 > 20)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [False, False,  True,  True,  True],
       [ True,  True, False,  True,  True]])

In [34]:
arr3[~(arr3>20)]

array([  1.   ,   3.   ,   5.   ,  -7.   , -90.   ,  -2.   ,   4.   ,
        -6.   ,   8.   ,  10.   ,  -2.   ,  -5.   ,  -8.   , -66.   ,
       -22.   ,   9.   ,  13.114])

In [35]:
(arr3 > 5) & (arr3 < 15)

array([[False, False, False, False, False],
       [False, False, False,  True,  True],
       [False, False, False, False, False],
       [False, False, False,  True,  True]])

In [36]:
arr3[(arr3>5) & (arr3<15)]

array([ 8.   , 10.   ,  9.   , 13.114])

# 花式索引 P21

In [37]:
arr3

array([[  1.   ,   3.   ,   5.   ,  -7.   , -90.   ],
       [ -2.   ,   4.   ,  -6.   ,   8.   ,  10.   ],
       [ 22.   ,  33.   ,  -2.   ,  -5.   ,  -8.   ],
       [-66.   , -22.   ,  33.   ,   9.   ,  13.114]])

In [38]:
# 第三行和第二行  
arr3[[2,1]]

array([[22., 33., -2., -5., -8.],
       [-2.,  4., -6.,  8., 10.]])

In [39]:
arr3[[2,1],[1,2]] # 相当于arr3[2,1] arr3[1,2]

array([33., -6.])

In [40]:
arr3[2,1]

33.0

In [41]:
arr3[1,2]

-6.0

In [42]:
arr3[:,[3,1]] # 相当于arr3[:,3] arr3[:,1]

array([[ -7.,   3.],
       [  8.,   4.],
       [ -5.,  33.],
       [  9., -22.]])

In [43]:
arr3[:,3]

array([-7.,  8., -5.,  9.])

In [44]:
arr3[:,1]

array([  3.,   4.,  33., -22.])

In [45]:
arr3[:,[3]]

array([[-7.],
       [ 8.],
       [-5.],
       [ 9.]])

In [46]:
arr3[:,[1]]

array([[  3.],
       [  4.],
       [ 33.],
       [-22.]])

In [47]:
arr3

array([[  1.   ,   3.   ,   5.   ,  -7.   , -90.   ],
       [ -2.   ,   4.   ,  -6.   ,   8.   ,  10.   ],
       [ 22.   ,  33.   ,  -2.   ,  -5.   ,  -8.   ],
       [-66.   , -22.   ,  33.   ,   9.   ,  13.114]])

In [48]:
arr3[[1,-1],[1,0]]

array([  4., -66.])

In [49]:
# ix_
arr3[np.ix_([0,-1],[1,0,3])]

array([[  3.,   1.,  -7.],
       [-22., -66.,   9.]])

In [50]:
arr3[[0,-1]][:,[1,0,3]]

array([[  3.,   1.,  -7.],
       [-22., -66.,   9.]])

In [51]:
np.ix_([0,-1],[1,0,3])

(array([[ 0],
        [-1]]),
 array([[1, 0, 3]]))

# 数组形状改变 P22

In [52]:
arr3

array([[  1.   ,   3.   ,   5.   ,  -7.   , -90.   ],
       [ -2.   ,   4.   ,  -6.   ,   8.   ,  10.   ],
       [ 22.   ,  33.   ,  -2.   ,  -5.   ,  -8.   ],
       [-66.   , -22.   ,  33.   ,   9.   ,  13.114]])

In [53]:
arr4 = arr3.copy()

In [54]:
arr4

array([[  1.   ,   3.   ,   5.   ,  -7.   , -90.   ],
       [ -2.   ,   4.   ,  -6.   ,   8.   ,  10.   ],
       [ 22.   ,  33.   ,  -2.   ,  -5.   ,  -8.   ],
       [-66.   , -22.   ,  33.   ,   9.   ,  13.114]])

In [55]:
# 不改变原视图
arr4.reshape(10,2)

array([[  1.   ,   3.   ],
       [  5.   ,  -7.   ],
       [-90.   ,  -2.   ],
       [  4.   ,  -6.   ],
       [  8.   ,  10.   ],
       [ 22.   ,  33.   ],
       [ -2.   ,  -5.   ],
       [ -8.   , -66.   ],
       [-22.   ,  33.   ],
       [  9.   ,  13.114]])

In [56]:
arr4

array([[  1.   ,   3.   ,   5.   ,  -7.   , -90.   ],
       [ -2.   ,   4.   ,  -6.   ,   8.   ,  10.   ],
       [ 22.   ,  33.   ,  -2.   ,  -5.   ,  -8.   ],
       [-66.   , -22.   ,  33.   ,   9.   ,  13.114]])

In [57]:
arr3

array([[  1.   ,   3.   ,   5.   ,  -7.   , -90.   ],
       [ -2.   ,   4.   ,  -6.   ,   8.   ,  10.   ],
       [ 22.   ,  33.   ,  -2.   ,  -5.   ,  -8.   ],
       [-66.   , -22.   ,  33.   ,   9.   ,  13.114]])

In [58]:
# 改变原视图
arr3.resize(10,2)

In [59]:
arr3

array([[  1.   ,   3.   ],
       [  5.   ,  -7.   ],
       [-90.   ,  -2.   ],
       [  4.   ,  -6.   ],
       [  8.   ,  10.   ],
       [ 22.   ,  33.   ],
       [ -2.   ,  -5.   ],
       [ -8.   , -66.   ],
       [-22.   ,  33.   ],
       [  9.   ,  13.114]])

In [60]:
arr4

array([[  1.   ,   3.   ,   5.   ,  -7.   , -90.   ],
       [ -2.   ,   4.   ,  -6.   ,   8.   ,  10.   ],
       [ 22.   ,  33.   ,  -2.   ,  -5.   ,  -8.   ],
       [-66.   , -22.   ,  33.   ,   9.   ,  13.114]])

In [91]:
arr5 = arr4.copy()

In [92]:
arr5

array([[  1.   ,   3.   ],
       [  5.   ,  -7.   ],
       [-90.   ,  -2.   ],
       [  4.   ,  -6.   ],
       [  8.   ,  10.   ],
       [ 22.   ,  33.   ],
       [ -2.   ,  -5.   ],
       [ -8.   , -66.   ],
       [-22.   ,  33.   ],
       [  9.   ,  13.114]])

In [63]:
# shape也改变自身
arr4.shape = (10,2)

In [64]:
arr4

array([[  1.   ,   3.   ],
       [  5.   ,  -7.   ],
       [-90.   ,  -2.   ],
       [  4.   ,  -6.   ],
       [  8.   ,  10.   ],
       [ 22.   ,  33.   ],
       [ -2.   ,  -5.   ],
       [ -8.   , -66.   ],
       [-22.   ,  33.   ],
       [  9.   ,  13.114]])

In [65]:
arr3

array([[  1.   ,   3.   ],
       [  5.   ,  -7.   ],
       [-90.   ,  -2.   ],
       [  4.   ,  -6.   ],
       [  8.   ,  10.   ],
       [ 22.   ,  33.   ],
       [ -2.   ,  -5.   ],
       [ -8.   , -66.   ],
       [-22.   ,  33.   ],
       [  9.   ,  13.114]])

In [66]:
arr4

array([[  1.   ,   3.   ],
       [  5.   ,  -7.   ],
       [-90.   ,  -2.   ],
       [  4.   ,  -6.   ],
       [  8.   ,  10.   ],
       [ 22.   ,  33.   ],
       [ -2.   ,  -5.   ],
       [ -8.   , -66.   ],
       [-22.   ,  33.   ],
       [  9.   ,  13.114]])

In [67]:
arr5

array([[  1.   ,   3.   ,   5.   ,  -7.   , -90.   ],
       [ -2.   ,   4.   ,  -6.   ,   8.   ,  10.   ],
       [ 22.   ,  33.   ,  -2.   ,  -5.   ,  -8.   ],
       [-66.   , -22.   ,  33.   ,   9.   ,  13.114]])

In [68]:
# ravel - 降维,横向
arr5.ravel()

array([  1.   ,   3.   ,   5.   ,  -7.   , -90.   ,  -2.   ,   4.   ,
        -6.   ,   8.   ,  10.   ,  22.   ,  33.   ,  -2.   ,  -5.   ,
        -8.   , -66.   , -22.   ,  33.   ,   9.   ,  13.114])

In [69]:
arr5

array([[  1.   ,   3.   ,   5.   ,  -7.   , -90.   ],
       [ -2.   ,   4.   ,  -6.   ,   8.   ,  10.   ],
       [ 22.   ,  33.   ,  -2.   ,  -5.   ,  -8.   ],
       [-66.   , -22.   ,  33.   ,   9.   ,  13.114]])

In [70]:
# 纵向
# ravel - 缠绕
arr5.ravel(order = 'F')

array([  1.   ,  -2.   ,  22.   , -66.   ,   3.   ,   4.   ,  33.   ,
       -22.   ,   5.   ,  -6.   ,  -2.   ,  33.   ,  -7.   ,   8.   ,
        -5.   ,   9.   , -90.   ,  10.   ,  -8.   ,  13.114])

In [71]:
arr5

array([[  1.   ,   3.   ,   5.   ,  -7.   , -90.   ],
       [ -2.   ,   4.   ,  -6.   ,   8.   ,  10.   ],
       [ 22.   ,  33.   ,  -2.   ,  -5.   ,  -8.   ],
       [-66.   , -22.   ,  33.   ,   9.   ,  13.114]])

In [72]:
# flatten - 使变平，横向
arr5.flatten()

array([  1.   ,   3.   ,   5.   ,  -7.   , -90.   ,  -2.   ,   4.   ,
        -6.   ,   8.   ,  10.   ,  22.   ,  33.   ,  -2.   ,  -5.   ,
        -8.   , -66.   , -22.   ,  33.   ,   9.   ,  13.114])

In [73]:
arr5

array([[  1.   ,   3.   ,   5.   ,  -7.   , -90.   ],
       [ -2.   ,   4.   ,  -6.   ,   8.   ,  10.   ],
       [ 22.   ,  33.   ,  -2.   ,  -5.   ,  -8.   ],
       [-66.   , -22.   ,  33.   ,   9.   ,  13.114]])

In [74]:
# 纵向
arr5.flatten(order = 'F')

array([  1.   ,  -2.   ,  22.   , -66.   ,   3.   ,   4.   ,  33.   ,
       -22.   ,   5.   ,  -6.   ,  -2.   ,  33.   ,  -7.   ,   8.   ,
        -5.   ,   9.   , -90.   ,  10.   ,  -8.   ,  13.114])

In [75]:
arr5

array([[  1.   ,   3.   ,   5.   ,  -7.   , -90.   ],
       [ -2.   ,   4.   ,  -6.   ,   8.   ,  10.   ],
       [ 22.   ,  33.   ,  -2.   ,  -5.   ,  -8.   ],
       [-66.   , -22.   ,  33.   ,   9.   ,  13.114]])

In [76]:
# 两行
arr5.reshape(2,-1)

array([[  1.   ,   3.   ,   5.   ,  -7.   , -90.   ,  -2.   ,   4.   ,
         -6.   ,   8.   ,  10.   ],
       [ 22.   ,  33.   ,  -2.   ,  -5.   ,  -8.   , -66.   , -22.   ,
         33.   ,   9.   ,  13.114]])

In [77]:
arr5.reshape(-1)

array([  1.   ,   3.   ,   5.   ,  -7.   , -90.   ,  -2.   ,   4.   ,
        -6.   ,   8.   ,  10.   ,  22.   ,  33.   ,  -2.   ,  -5.   ,
        -8.   , -66.   , -22.   ,  33.   ,   9.   ,  13.114])

In [78]:
arr5.reshape(-1,2)

array([[  1.   ,   3.   ],
       [  5.   ,  -7.   ],
       [-90.   ,  -2.   ],
       [  4.   ,  -6.   ],
       [  8.   ,  10.   ],
       [ 22.   ,  33.   ],
       [ -2.   ,  -5.   ],
       [ -8.   , -66.   ],
       [-22.   ,  33.   ],
       [  9.   ,  13.114]])

In [79]:
arr5.reshape(-1,1)

array([[  1.   ],
       [  3.   ],
       [  5.   ],
       [ -7.   ],
       [-90.   ],
       [ -2.   ],
       [  4.   ],
       [ -6.   ],
       [  8.   ],
       [ 10.   ],
       [ 22.   ],
       [ 33.   ],
       [ -2.   ],
       [ -5.   ],
       [ -8.   ],
       [-66.   ],
       [-22.   ],
       [ 33.   ],
       [  9.   ],
       [ 13.114]])

In [97]:
arr5

array([[  1.   ,   3.   ,   5.   ,  -7.   , -90.   ],
       [ -2.   ,   4.   ,  -6.   ,   8.   ,  10.   ],
       [ 22.   ,  33.   ,  -2.   ,  -5.   ,  -8.   ],
       [-66.   , -22.   ,  33.   ,   9.   ,  13.114]])

In [98]:
arr6 = arr5.copy()

In [99]:
arr6

array([[  1.   ,   3.   ,   5.   ,  -7.   , -90.   ],
       [ -2.   ,   4.   ,  -6.   ,   8.   ,  10.   ],
       [ 22.   ,  33.   ,  -2.   ,  -5.   ,  -8.   ],
       [-66.   , -22.   ,  33.   ,   9.   ,  13.114]])

In [100]:
arr5 = arr5.ravel()

In [101]:
arr5

array([  1.   ,   3.   ,   5.   ,  -7.   , -90.   ,  -2.   ,   4.   ,
        -6.   ,   8.   ,  10.   ,  22.   ,  33.   ,  -2.   ,  -5.   ,
        -8.   , -66.   , -22.   ,  33.   ,   9.   ,  13.114])

In [103]:
# ndim - 维度
arr5.ndim

1

In [104]:
# 行和列
arr5.shape

(20,)

In [105]:
arr6.shape

(4, 5)

In [106]:
arr5

array([  1.   ,   3.   ,   5.   ,  -7.   , -90.   ,  -2.   ,   4.   ,
        -6.   ,   8.   ,  10.   ,  22.   ,  33.   ,  -2.   ,  -5.   ,
        -8.   , -66.   , -22.   ,  33.   ,   9.   ,  13.114])

In [110]:
# 增加维度
arr5[np.newaxis,:].shape

(1, 20)

In [111]:
arr5

array([  1.   ,   3.   ,   5.   ,  -7.   , -90.   ,  -2.   ,   4.   ,
        -6.   ,   8.   ,  10.   ,  22.   ,  33.   ,  -2.   ,  -5.   ,
        -8.   , -66.   , -22.   ,  33.   ,   9.   ,  13.114])

In [114]:
# 增加到列
arr5[:,np.newaxis]

array([[  1.   ],
       [  3.   ],
       [  5.   ],
       [ -7.   ],
       [-90.   ],
       [ -2.   ],
       [  4.   ],
       [ -6.   ],
       [  8.   ],
       [ 10.   ],
       [ 22.   ],
       [ 33.   ],
       [ -2.   ],
       [ -5.   ],
       [ -8.   ],
       [-66.   ],
       [-22.   ],
       [ 33.   ],
       [  9.   ],
       [ 13.114]])

In [115]:
arr5[:,np.newaxis].shape

(20, 1)

In [116]:
arr5[:,np.newaxis].ndim

2

In [117]:
arr6

array([[  1.   ,   3.   ,   5.   ,  -7.   , -90.   ],
       [ -2.   ,   4.   ,  -6.   ,   8.   ,  10.   ],
       [ 22.   ,  33.   ,  -2.   ,  -5.   ,  -8.   ],
       [-66.   , -22.   ,  33.   ,   9.   ,  13.114]])

In [124]:
# delete - 删除（目标，行，列）
arr6 = np.delete(arr6,0,0)

In [125]:
arr6

array([[ -2.   ,   4.   ,  -6.   ,   8.   ,  10.   ],
       [ 22.   ,  33.   ,  -2.   ,  -5.   ,  -8.   ],
       [-66.   , -22.   ,  33.   ,   9.   ,  13.114]])

In [119]:
arr7 = np.arange(12).reshape(3,4)

In [120]:
arr7

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [126]:
# 横向合并
np.hstack((arr6,arr7))

array([[ -2.   ,   4.   ,  -6.   ,   8.   ,  10.   ,   0.   ,   1.   ,
          2.   ,   3.   ],
       [ 22.   ,  33.   ,  -2.   ,  -5.   ,  -8.   ,   4.   ,   5.   ,
          6.   ,   7.   ],
       [-66.   , -22.   ,  33.   ,   9.   ,  13.114,   8.   ,   9.   ,
         10.   ,  11.   ]])

In [132]:
# 同上
# concatenate - 连锁状
np.concatenate((arr6,arr7), axis = 1)

array([[ -2.   ,  -6.   ,   8.   ,  10.   ,   0.   ,   1.   ,   2.   ,
          3.   ],
       [ 22.   ,  -2.   ,  -5.   ,  -8.   ,   4.   ,   5.   ,   6.   ,
          7.   ],
       [-66.   ,  33.   ,   9.   ,  13.114,   8.   ,   9.   ,  10.   ,
         11.   ]])

In [129]:
# 删除一列
arr6 = np.delete(arr6,1,1)

In [130]:
arr6

array([[ -2.   ,  -6.   ,   8.   ,  10.   ],
       [ 22.   ,  -2.   ,  -5.   ,  -8.   ],
       [-66.   ,  33.   ,   9.   ,  13.114]])

In [128]:
arr7

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [131]:
# 纵向合并
np.vstack((arr6,arr7))

array([[ -2.   ,  -6.   ,   8.   ,  10.   ],
       [ 22.   ,  -2.   ,  -5.   ,  -8.   ],
       [-66.   ,  33.   ,   9.   ,  13.114],
       [  0.   ,   1.   ,   2.   ,   3.   ],
       [  4.   ,   5.   ,   6.   ,   7.   ],
       [  8.   ,   9.   ,  10.   ,  11.   ]])

In [133]:
# 同上
np.concatenate((arr6,arr7), axis=0)

array([[ -2.   ,  -6.   ,   8.   ,  10.   ],
       [ 22.   ,  -2.   ,  -5.   ,  -8.   ],
       [-66.   ,  33.   ,   9.   ,  13.114],
       [  0.   ,   1.   ,   2.   ,   3.   ],
       [  4.   ,   5.   ,   6.   ,   7.   ],
       [  8.   ,   9.   ,  10.   ,  11.   ]])

In [134]:
arr8 = np.array([0,1,2,3])

In [135]:
arr8

array([0, 1, 2, 3])

In [141]:
arr8 = arr8.reshape(2,2)

In [142]:
arr8

array([[0, 1],
       [2, 3]])

In [143]:
# 复制（x,y)份，沿x行，y列复制
np.tile(arr8,(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [2, 3, 2, 3, 2, 3, 2, 3],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [2, 3, 2, 3, 2, 3, 2, 3],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [2, 3, 2, 3, 2, 3, 2, 3],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [2, 3, 2, 3, 2, 3, 2, 3]])

In [145]:
np.tile(arr8,(4,4)).shape

(8, 8)

In [146]:
# 三维数组
arr9 = np.arange(8).reshape(2,2,2)

In [147]:
arr9

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [148]:
arr9.ndim

3

In [149]:
arr9.shape

(2, 2, 2)

In [150]:
arr9[0][0][0]

0

In [151]:
arr9[1][1][0]

6