In [1]:
import numpy as np

In [3]:
arr1 = np.array([-1,3,-5,7,-9])

In [5]:
arr1

array([-1,  3, -5,  7, -9])

In [8]:
# dtype - 规定数据类型
arr2 = np.array([2,-4,6,-8,10], dtype = 'float')

In [9]:
arr2

array([ 2., -4.,  6., -8., 10.])

In [10]:
arr3 = np.array([1,2,3,-4,-5,-6], dtype = 'str')

In [11]:
arr3

array(['1', '2', '3', '-4', '-5', '-6'], dtype='<U2')

In [14]:
# 二维数组，嵌套写
arr4 = np.array([[1,3,5,7],[2,4,5,7],[3,3,5,6]])

In [15]:
arr4

array([[1, 3, 5, 7],
       [2, 4, 5, 7],
       [3, 3, 5, 6]])

In [20]:
# 0-10
print(np.arange(0,10))
# 0-10,步长为05
print(np.arange(0,10,0.5))

[0 1 2 3 4 5 6 7 8 9]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]


In [25]:
# linspace - 等差数列
print(np.linspace(1,10,10))
#                 1-10,10个
print(np.linspace(1,10,13))
#                 1-10,13个

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.    1.75  2.5   3.25  4.    4.75  5.5   6.25  7.    7.75  8.5   9.25
 10.  ]


In [29]:
print(np.linspace(1,10,10,endpoint = False))
# 生成10个，但取不到最后一个数
# 相当于
print(np.linspace(1,10,11))
# 舍去10

[1.  1.9 2.8 3.7 4.6 5.5 6.4 7.3 8.2 9.1]
[ 1.   1.9  2.8  3.7  4.6  5.5  6.4  7.3  8.2  9.1 10. ]


In [30]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [32]:
# 等比函数
np.logspace(1,5,base = 2, num = 10)
# 以2为底,1-5的10个数为指数

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [34]:
# 相当于
2 ** np.linspace(1,5,10)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [33]:
np.logspace(2,8,num=4,base=2)
# 以2为底,2-8的4个数为指数

array([  4.,  16.,  64., 256.])

In [43]:
# zeros - 创建全为0的数组
print(np.zeros((2,3)))
print('\n')
print(np.zeros(5))
print('\n')
print(np.zeros((3,1)))

[[0. 0. 0.]
 [0. 0. 0.]]


[0. 0. 0. 0. 0.]


[[0.]
 [0.]
 [0.]]


In [44]:
# ones - 创建全为1的数组
print(np.ones((2,3)))
print('\n')
print(np.ones(5))
print('\n')
print(np.ones((3,1)))

[[1. 1. 1.]
 [1. 1. 1.]]


[1. 1. 1. 1. 1.]


[[1.]
 [1.]
 [1.]]


In [45]:
# eye - 创建单位矩阵
# 主对角线全为1
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [46]:
# diag - 对焦矩阵
np.diag([3,6,9])

array([[3, 0, 0],
       [0, 6, 0],
       [0, 0, 9]])

In [47]:
np.diag([3,6,9])+1
# 所有元素+1

array([[ 4,  1,  1],
       [ 1,  7,  1],
       [ 1,  1, 10]])

In [48]:
arr4

array([[1, 3, 5, 7],
       [2, 4, 5, 7],
       [3, 3, 5, 6]])

In [50]:
# 几行几列 
arr4.shape

(3, 4)

In [51]:
# 维度 - 行与列
arr4.ndim

2

In [52]:
# 一维数组
arr1.ndim

1

In [53]:
arr1.shape

(5,)

In [54]:
arr4.dtype

dtype('int32')

In [56]:
arr3.dtype

dtype('<U2')