# P29 Numpy线性代数

In [6]:
import numpy as np

In [2]:
a=[1,2,3]
b=[4,5,6]

In [4]:
np.dot(a,b)
# dot - 矩阵乘法,1*4+2*5+3*6=32

32

In [7]:
arr = np.array([1,2,3,4]).reshape(4,1)

In [8]:
arr

array([[1],
       [2],
       [3],
       [4]])

In [9]:
np.matrix([1,2,3,4])

matrix([[1, 2, 3, 4]])

In [11]:
arr1 = np.arange(12).reshape(3,4)

In [12]:
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
np.dot(arr1,arr)
# 1*0+2*1+3*2+4*3=20
# 1*4+2*5+3*6+4*7=60
# 1*8+2*9+3*10+4*11=100

array([[ 20],
       [ 60],
       [100]])

In [14]:
arr2 = np.array([[1,3],[5,7]])

In [15]:
arr2

array([[1, 3],
       [5, 7]])

In [16]:
arr3 = np.array([[-2,-4],[-6,-8]])

In [17]:
arr3

array([[-2, -4],
       [-6, -8]])

In [24]:
np.dot(arr2,arr3)
# 1*-2+3*-6=-20
# 1*-4+3*-8=-28
# 5*-2+7*-6=-52
# 5*-4+7*-8=-76

array([[-20, -28],
       [-52, -76]])

In [26]:
arr2 * arr3
# 1*-2
# 3*-4
# 5*-6
# 7*-8

array([[ -2, -12],
       [-30, -56]])

In [62]:
arr2 = np.array([1,2,3,4,5,6,7,8,9,10,-1,-2,-3,-4,-5,-6,-7,-8,-9,-10,1.2,1.3,1.4,1.5,1.6]).reshape(5,5)

In [71]:
arr3 = np.array([1,2,3,4,5,6,7,8,9,10,-1,-2,-3,-4,-5,-6,-7,-8,-9,-10,1.2,1.3,1.4,1.5,1.6]).reshape(5,5)

In [63]:
arr2

array([[  1. ,   2. ,   3. ,   4. ,   5. ],
       [  6. ,   7. ,   8. ,   9. ,  10. ],
       [ -1. ,  -2. ,  -3. ,  -4. ,  -5. ],
       [ -6. ,  -7. ,  -8. ,  -9. , -10. ],
       [  1.2,   1.3,   1.4,   1.5,   1.6]])

In [64]:
# transpose - 颠倒、置换
# transpose() - 矩阵转置
arr2 = np.transpose(arr2)

In [65]:
arr2

array([[  1. ,   6. ,  -1. ,  -6. ,   1.2],
       [  2. ,   7. ,  -2. ,  -7. ,   1.3],
       [  3. ,   8. ,  -3. ,  -8. ,   1.4],
       [  4. ,   9. ,  -4. ,  -9. ,   1.5],
       [  5. ,  10. ,  -5. , -10. ,   1.6]])

In [66]:
arr2 = arr2[:2,:2]

In [67]:
arr2

array([[1., 6.],
       [2., 7.]])

In [68]:
# linalg.inv() - 求逆矩阵
arr2_inv = np.linalg.inv(arr2)
# (1 2)(a b)   (1 0)
#            = 
# (2 7)(c d)   (0 1)
# a=-1.4
# b=1.2
# c=0.4
# d=-0.2

In [69]:
arr2_inv

array([[-1.4,  1.2],
       [ 0.4, -0.2]])

In [70]:
# 相乘为单位矩阵
np.dot(arr2_inv,arr2)

array([[1., 0.],
       [0., 1.]])

In [75]:
arr3

array([[  1. ,   2. ,   3. ,   4. ,   5. ],
       [  6. ,   7. ,   8. ,   9. ,  10. ],
       [ -1. ,  -2. ,  -3. ,  -4. ,  -5. ],
       [ -6. ,  -7. ,  -8. ,  -9. , -10. ],
       [  1.2,   1.3,   1.4,   1.5,   1.6]])

In [74]:
# diag() - 对角线元素
np.diag(arr3)

array([ 1. ,  7. , -3. , -9. ,  1.6])

###### 矩阵求方程组

In [76]:
# linalg.solve()

x+2y+3z = 26
2x+3y+z = 36
3x+2y+z = 69

In [99]:
A = np.array([[1,2,3],[2,3,1],[3,1,2]])
B = np.array([[26],[36],[69]])

In [101]:
X = np.linalg.solve(A,B)

In [102]:
X

array([[18.23809524],
       [-3.04761905],
       [ 8.66666667]])

In [103]:
# 验证
np.dot(A,X)

array([[26.],
       [36.],
       [69.]])