# P25 Numpy运用，文件读写

In [1]:
import numpy as np

In [4]:
# genfromtxt - 导入数据的一种方式
# delimiter - 分隔符
data = np.genfromtxt(r'E:\云开见明\云开见明Python数据分析师课程数据（仅与云开见明Python数据分析师配套）\第二章\arr.txt',delimiter=',')

In [22]:
# genfromtxt - 方法介绍
np.genfromtxt?

In [5]:
data

array([[0.15896 , 0.153071, 0.69553 , 0.318766, 0.69197 , 0.554383,
        0.388951],
       [0.925132, 0.84167 , 0.357398, 0.043591, 0.304768, 0.398186,
        0.704959],
       [0.995358, 0.355915, 0.762548, 0.593177, 0.691702, 0.151127,
        0.398876],
       [0.240856, 0.343456, 0.513128, 0.666625, 0.105908, 0.130895,
        0.321981],
       [0.661564, 0.846506, 0.553257, 0.854452, 0.384838, 0.316788,
        0.354265],
       [0.171082, 0.829113, 0.338671, 0.55237 , 0.578551, 0.521533,
        0.002688],
       [0.988345, 0.905342, 0.207636, 0.292489, 0.52001 , 0.901911,
        0.983631]])

In [7]:
type(data)

numpy.ndarray

In [13]:
# skip_header - 跳过表头
data_1 = np.genfromtxt(r'E:\云开见明\云开见明Python数据分析师课程数据（仅与云开见明Python数据分析师配套）\第二章\sales.csv',delimiter=',',skip_header=1)

In [14]:
data_1

array([[4.149e+01, 2.902e+01, 3.770e+00, 8.460e+00, 8.274e+01],
       [2.908e+01, 3.580e+00, 6.810e+00, 7.700e-01, 4.024e+01],
       [1.585e+01, 1.288e+01, 3.790e+00, 3.310e+00, 3.582e+01],
       ...,
       [0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 1.000e-02],
       [0.000e+00, 1.000e-02, 0.000e+00, 0.000e+00, 1.000e-02],
       [1.000e-02, 0.000e+00, 0.000e+00, 0.000e+00, 1.000e-02]])

In [18]:
# loadtxt作用同genfromtxt
data_2 = np.loadtxt(r'E:\云开见明\云开见明Python数据分析师课程数据（仅与云开见明Python数据分析师配套）\第二章\arr.txt',delimiter = ',')

In [21]:
np.loadtxt?

In [19]:
data_2

array([[0.15896 , 0.153071, 0.69553 , 0.318766, 0.69197 , 0.554383,
        0.388951],
       [0.925132, 0.84167 , 0.357398, 0.043591, 0.304768, 0.398186,
        0.704959],
       [0.995358, 0.355915, 0.762548, 0.593177, 0.691702, 0.151127,
        0.398876],
       [0.240856, 0.343456, 0.513128, 0.666625, 0.105908, 0.130895,
        0.321981],
       [0.661564, 0.846506, 0.553257, 0.854452, 0.384838, 0.316788,
        0.354265],
       [0.171082, 0.829113, 0.338671, 0.55237 , 0.578551, 0.521533,
        0.002688],
       [0.988345, 0.905342, 0.207636, 0.292489, 0.52001 , 0.901911,
        0.983631]])

# numpy存储数据

In [24]:
data

array([[0.15896 , 0.153071, 0.69553 , 0.318766, 0.69197 , 0.554383,
        0.388951],
       [0.925132, 0.84167 , 0.357398, 0.043591, 0.304768, 0.398186,
        0.704959],
       [0.995358, 0.355915, 0.762548, 0.593177, 0.691702, 0.151127,
        0.398876],
       [0.240856, 0.343456, 0.513128, 0.666625, 0.105908, 0.130895,
        0.321981],
       [0.661564, 0.846506, 0.553257, 0.854452, 0.384838, 0.316788,
        0.354265],
       [0.171082, 0.829113, 0.338671, 0.55237 , 0.578551, 0.521533,
        0.002688],
       [0.988345, 0.905342, 0.207636, 0.292489, 0.52001 , 0.901911,
        0.983631]])

In [25]:
# np.savetxt(path,data,delimiter,fmt)
# fmt - 存储数据格式

In [27]:
# 保存为 test.txt 文件
np.savetxt(r'E:\云开见明\云开见明Python数据分析师课程数据（仅与云开见明Python数据分析师配套）\第二章\test.txt',data,delimiter = ',',fmt = '%.3f')

In [28]:
# 读取 test.txt 文件
np.genfromtxt(r'E:\云开见明\云开见明Python数据分析师课程数据（仅与云开见明Python数据分析师配套）\第二章\test.txt',delimiter = ',')

array([[0.159, 0.153, 0.696, 0.319, 0.692, 0.554, 0.389],
       [0.925, 0.842, 0.357, 0.044, 0.305, 0.398, 0.705],
       [0.995, 0.356, 0.763, 0.593, 0.692, 0.151, 0.399],
       [0.241, 0.343, 0.513, 0.667, 0.106, 0.131, 0.322],
       [0.662, 0.847, 0.553, 0.854, 0.385, 0.317, 0.354],
       [0.171, 0.829, 0.339, 0.552, 0.579, 0.522, 0.003],
       [0.988, 0.905, 0.208, 0.292, 0.52 , 0.902, 0.984]])

# P26 Numpy字符串处理

In [1]:
str_list = ['Hello','World']

In [3]:
[i.upper() for i in str_list]

['HELLO', 'WORLD']

In [4]:
import numpy as np

In [11]:
# numpy方法
# 字母大写
str_arr = np.char.upper(str_list)

In [8]:
str_arr

array(['HELLO', 'WORLD'], dtype='<U5')

In [12]:
# 字符串拼接
np.char.add(['steam#','origin#'],['wegame#','epic#'])

array(['steam#wegame#', 'origin#epic#'], dtype='<U14')

In [13]:
np.char.multiply(['steam#','origin#'],3)

array(['steam#steam#steam#', 'origin#origin#origin#'], dtype='<U21')

In [14]:
# 列表推导式
[i*3 for i in ['steam','origin']]

['steamsteamsteam', 'originoriginorigin']

In [17]:
# char.join() - 分隔
np.char.join(['+','-'],['hello','world'])

array(['h+e+l+l+o', 'w-o-r-l-d'], dtype='<U9')

In [19]:
# char.replace() - 替换
a = ['steam ','is ','garbage']
np.char.replace(a,'gar','666')

array(['steam ', 'is ', '666bage'], dtype='<U7')

In [20]:
# 推导式
[i.replace('gar','666') for i in a]

['steam ', 'is ', '666bage']

In [21]:
# char.strip() - 去掉字符串,只能去开头结尾
b = ['*腾讯*','*阿狸-','+陈瑞*']
np.char.strip(b,'*')

array(['腾讯', '阿狸-', '+陈瑞'], dtype='<U4')

In [22]:
f = open(r'E:\云开见明\云开见明Python数据分析师课程数据（仅与云开见明Python数据分析师配套）\第一章\equipment_1.txt',encoding = 'utf-8').readlines()

In [23]:
f

['运营商\t设备型号\t设备名称\t系统版本\t内存容量\t操作系统\t内存剩余容量\tMAC地址\tIP地址\t是否root\t是否使用模拟器\t设备身份码\t电池电量\tsim卡状态(服务状态)\tsim卡状态(漫游)\tsim卡状态(移动网络状态)\tsd卡容量\t分辨率\t抓取时间\t客户姓名\t客户手机号\t客户身份证号\t客户注册时间\n',
 '中国电信\t"GOME S1"\taus6737t_66_m0\t6.0\t"25.19 GB"\tAndroid6.0\t"17.72 GB"\t20:f4:52:06:24:69\t192.168.1.100\t0\t0\tA1000053232DD2\t79%\t良好\t非漫游\t已连接\t"25.19 GB"\t720*1280像素\t"2018-05-14 15:06:48"\t王茜\t134X8916636\t5101XX198007230626\t"2018-04-04 12:02:47"\n',
 'CMCC\t"vivo Y67"\tPD1612\t6.0\t"24.55 GB"\tAndroid6.0\t"2.40 GB"\t02:00:00:00:00:00\t192.168.0.102\t0\t0\t863600031885927\t22%\t良好\t非漫游\t已连接\t"24.55 GB"\t720*1280像素\t"2018-04-21 19:37:49"\t回龙涛\t187X0193126\t1305XX199202083018\t"2018-04-21 19:37:49"\n',
 '中国电信\t"vivo X9"\tPD1616\t7.1.2\t"52.96 GB"\tAndroid7.1.2\t"29.28 GB"\t02:00:00:00:00:00\t192.168.0.105\t0\t0\t864161030857010\t54%\t良好\t非漫游\t已连接\t"52.37 GB"\t1080*1920像素\t"2018-04-26 15:22:01"\t韦晓平\t1557X867751\t45260XX98611161833\t"2018-04-24 13:47:03"\n',
 '中国电信\t"vivo X9"\tPD1616\t7.1.2\t"52.96 GB"

In [24]:
f[0]

'运营商\t设备型号\t设备名称\t系统版本\t内存容量\t操作系统\t内存剩余容量\tMAC地址\tIP地址\t是否root\t是否使用模拟器\t设备身份码\t电池电量\tsim卡状态(服务状态)\tsim卡状态(漫游)\tsim卡状态(移动网络状态)\tsd卡容量\t分辨率\t抓取时间\t客户姓名\t客户手机号\t客户身份证号\t客户注册时间\n'

In [25]:
c = f[3]

In [26]:
c

'中国电信\t"vivo X9"\tPD1616\t7.1.2\t"52.96 GB"\tAndroid7.1.2\t"29.28 GB"\t02:00:00:00:00:00\t192.168.0.105\t0\t0\t864161030857010\t54%\t良好\t非漫游\t已连接\t"52.37 GB"\t1080*1920像素\t"2018-04-26 15:22:01"\t韦晓平\t1557X867751\t45260XX98611161833\t"2018-04-24 13:47:03"\n'

In [34]:
# split - 分隔
arr = c.split('\t')

In [35]:
arr

['中国电信',
 '"vivo X9"',
 'PD1616',
 '7.1.2',
 '"52.96 GB"',
 'Android7.1.2',
 '"29.28 GB"',
 '02:00:00:00:00:00',
 '192.168.0.105',
 '0',
 '0',
 '864161030857010',
 '54%',
 '良好',
 '非漫游',
 '已连接',
 '"52.37 GB"',
 '1080*1920像素',
 '"2018-04-26 15:22:01"',
 '韦晓平',
 '1557X867751',
 '45260XX98611161833',
 '"2018-04-24 13:47:03"\n']

In [36]:
# strip(x,y) - 删除两边
# rstrip - 删除右边
# lstrip - 删除左边
arr = np.char.rstrip(arr,'\n')

In [37]:
arr

array(['中国电信', '"vivo X9"', 'PD1616', '7.1.2', '"52.96 GB"',
       'Android7.1.2', '"29.28 GB"', '02:00:00:00:00:00', '192.168.0.105',
       '0', '0', '864161030857010', '54%', '良好', '非漫游', '已连接',
       '"52.37 GB"', '1080*1920像素', '"2018-04-26 15:22:01"', '韦晓平',
       '1557X867751', '45260XX98611161833', '"2018-04-24 13:47:03"'],
      dtype='<U22')

In [38]:
arr = np.char.replace(arr,'"',' ')

In [39]:
arr

array(['中国电信', ' vivo X9 ', 'PD1616', '7.1.2', ' 52.96 GB ',
       'Android7.1.2', ' 29.28 GB ', '02:00:00:00:00:00', '192.168.0.105',
       '0', '0', '864161030857010', '54%', '良好', '非漫游', '已连接',
       ' 52.37 GB ', '1080*1920像素', ' 2018-04-26 15:22:01 ', '韦晓平',
       '1557X867751', '45260XX98611161833', ' 2018-04-24 13:47:03 '],
      dtype='<U21')

In [40]:
# char.find - 字符串匹配
np.char.find(arr,'GB')

array([-1, -1, -1, -1,  7, -1,  7, -1, -1, -1, -1, -1, -1, -1, -1, -1,  7,
       -1, -1, -1, -1, -1, -1])

In [41]:
arr[4][7]

'G'

In [42]:
arr[6][8]

'B'

In [43]:
arr[-7][7]

'G'

In [44]:
# char.islower() - 判断是否全是小写
np.char.islower(arr)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])

In [45]:
# char.isdigit() - 是否只包含数字
np.char.isdigit(arr)

array([False, False, False, False, False, False, False, False, False,
        True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False])

In [49]:
arr[11]

'864161030857010'

In [47]:
arr

array(['中国电信', ' vivo X9 ', 'PD1616', '7.1.2', ' 52.96 GB ',
       'Android7.1.2', ' 29.28 GB ', '02:00:00:00:00:00', '192.168.0.105',
       '0', '0', '864161030857010', '54%', '良好', '非漫游', '已连接',
       ' 52.37 GB ', '1080*1920像素', ' 2018-04-26 15:22:01 ', '韦晓平',
       '1557X867751', '45260XX98611161833', ' 2018-04-24 13:47:03 '],
      dtype='<U21')

In [46]:
# char.isalpha() - 是否只包含字母
np.char.isalpha(arr)

array([ True, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True,  True, False, False,
       False,  True, False, False, False])

In [48]:
arr[0]

'中国电信'

In [50]:
# char.count() - 计算字符串出现次数
np.char.count(arr,'1')

array([0, 0, 2, 1, 0, 1, 0, 0, 3, 0, 0, 3, 0, 0, 0, 0, 0, 2, 3, 0, 2, 4,
       2])

In [51]:
arr[2]

'PD1616'

In [52]:
# char.startswith() - 判断是否以某字符串开头
np.char.startswith(arr,'1')

array([False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False,  True,
       False, False,  True, False, False])

In [53]:
arr[8]

'192.168.0.105'

In [54]:
# char.endswith() - 判断是否以某字符串结尾
np.char.endswith(arr,'1')

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False])

In [55]:
arr[-3]

'1557X867751'